### ISSUE TITLE
GitHub actions fail on all platforms due to integration E2E tests

### ISSUE THREAD

**Issue by dulanov** [ergo-services/ergo#111]
**Describe the bug**

GitHub actions always fail by E2E tests on all platforms but without any details.

**To Reproduce**

Always fail on CI/CD - https://github.com/ergo-services/ergo/actions

**Expected behavior**

Should be success, not fail.

**Screenshots**

https://github.com/ergo-services/ergo/actions/runs/3271054409/jobs/5380380573#step:4:1242

```
...

=== Test TCP Server
Starting nodes: nodeTCP1@localhost: OK
...starting process (gen.TCP): OK
...makeing a new connection: OK
...send/recv data (10 bytes as 1 logic dataframe): OK
...send/recv data (7 bytes as a part of logic dataframe): OK
...send/recv data (5 bytes, must be 1 logic dataframe + extra 2 bytes): OK
...send/recv data (8 bytes, must be 1 logic dataframe): OK
...stopping process (gen.TCP): OK
--- PASS: TestTCP (0.00s)
=== RUN   TestUDP

=== Test UDP Server
Starting nodes: nodeUDP1@localhost: OK
...starting process (gen.UDP): OK
...send/receive data: OK
...stopping process (gen.UDP): OK
--- PASS: TestUDP (0.00s)
=== RUN   TestWeb

=== Test Web Server
Starting nodes: nodeWeb1@localhost: OK
...starting process (gen.Web): OK
...making simple GET request: OK
--- PASS: TestWeb (0.00s)
FAIL
FAIL	github.com/ergo-services/ergo/tests	61.923s
FAIL
Error: Process completed with exit code 1.
```

**Environment (please complete the following information):**

Fail on all platforms, below env for Ubuntu:

```
Operating System
  Ubuntu
  20.0.5
  LTS

go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.17.13/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.17.13/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.17.13"
  GCCGO="gccgo"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/ergo/ergo/go.mod"
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1316604600=/tmp/go-build -gno-record-gcc-switches"
```

**Additional context**

I rerun it using [`gotestsum` command](https://pkg.go.dev/gotest.tools/gotestsum) and found out that each time the reason was different, for example, several variants:

https://github.com/dulanov/ergo/actions/runs/3315358118/jobs/5475849237#step:5:1

```
✖  tests (1m11.876s)

=== Failed
=== FAIL: tests TestNodeProxyConnect (3.29s)

=== Test Node Proxy
... connect NodeA to NodeC via NodeB: OK
... disconnect NodeC from NodeA: OK
... connect NodeA to NodeC via NodeB(transit proxy disabled): OK
... connect NodeA to NodeC (proxy feature support disabled) via NodeB: OK
... connect NodeA to NodeC (with wrong cookie) via NodeB: OK
... connect NodeA to NodeC (with correct cookie) via NodeB: OK
... connect NodeA to NodeD (with enabled encryption) via NodeB: OK
... start processA on NodeA: OK
... start processC on NodeC: OK
... start processD on NodeD: OK
... processA send short message to processC: OK
... processA send short message to processD (encrypted): OK
... processA send 10K message to processC (compressed): OK
... processA send 10K message to processD (compressed, encrypted): OK
... processA send 100K message to processC (fragmented):     server_test.go:897: result timeout

=== FAIL: tests TestServerMessageFlood (2.00s)

=== Test Server message flood 
Starting node: nodeGS1MessageFlood@localhost: OK
    wait for start of gs1source on "nodeGS1MessageFlood@localhost": OK
    wait for start of gs2source on "nodeGS1MessageFlood@localhost": OK
    wait for start of gs3source on "nodeGS1MessageFlood@localhost": OK
    wait for start of gs4source on "nodeGS1MessageFlood@localhost": OK
    wait for start of gs5source on "nodeGS1MessageFlood@localhost": OK
    wait for start of gsdest on "nodeGS1MessageFlood@localhost": OK
2022/10/24 18:57:19 WARNING! Server terminated <C58580E6.0.1014>["gs4source"]. Panic reason: "err on making a call: timed out" at github.com/ergo-services/ergo/tests.(*messageFloodSourceGS).HandleInfo[/home/runner/work/ergo/ergo/tests/server_test.go:675]
    server_test.go:897: result timeout

DONE 64 tests, 2 failures in 82.719s
Error: Process completed with exit code 1.
```

or https://github.com/dulanov/ergo/actions/runs/3315381867/jobs/5475904571#step:5:1

```
✖  tests (24.292s)

=== Failed
=== FAIL: tests TestNodeResolveExtra (unknown)

=== Test Node Resolve Extra 
... starting node1 with disabled TLS: OK
... starting node2 with enabled TLS: OK
... node1 resolves node2 with enabled TLS: OK
... node2 resolves node1 with disabled TLS: OK
... node1 connect to node2: OK
... disconnecting nodes: OK
... node2 connect to node1: --- FAIL: TestNodeResolveExtra (0.34s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 8317 [running]:
testing.tRunner.func1.2({0x14d8280, 0xc000152138})
	/Users/runner/hostedtoolcache/go/1.18.7/x64/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/Users/runner/hostedtoolcache/go/1.18.7/x64/src/testing/testing.go:1392 +0x39f
panic({0x14d8280, 0xc000152138})
	/Users/runner/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x207
github.com/ergo-services/ergo/tests.TestNodeResolveExtra(0xc0010a3380)
	/Users/runner/work/ergo/ergo/tests/node_test.go:574 +0xefa
testing.tRunner(0xc0010a3380, 0x1547ba8)
	/Users/runner/hostedtoolcache/go/1.18.7/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/Users/runner/hostedtoolcache/go/1.18.7/x64/src/testing/testing.go:1486 +0x35f

DONE 33 tests, 1 failure in 36.602s
Error: Process completed with exit code 1.
```

or  https://github.com/dulanov/ergo/actions/runs/3315396040/jobs/5475936433#step:5:1

```
✖  tests (57.031s)

=== Failed
=== FAIL: tests TestNodeProxyConnect (3.33s)

=== Test Node Proxy
... connect NodeA to NodeC via NodeB: OK
... disconnect NodeC from NodeA: OK
... connect NodeA to NodeC via NodeB(transit proxy disabled): OK
... connect NodeA to NodeC (proxy feature support disabled) via NodeB: OK
... connect NodeA to NodeC (with wrong cookie) via NodeB: OK
... connect NodeA to NodeC (with correct cookie) via NodeB: OK
... connect NodeA to NodeD (with enabled encryption) via NodeB: OK
... start processA on NodeA: OK
... start processC on NodeC: OK
... start processD on NodeD: OK
... processA send short message to processC: OK
... processA send short message to processD (encrypted): OK
... processA send 10K message to processC (compressed): OK
... processA send 10K message to processD (compressed, encrypted): OK
... processA send 100K message to processC (fragmented):     server_test.go:897: result timeout

=== FAIL: tests TestRaftGet (0.09s)

=== Test GenRaft - get data
    started raft process <20790EB2.0.1011> with serial 8
    started raft process <B7995A78.0.1011> with serial 5
    started raft process <A4BCA225.0.1011> with serial 6
    started raft process <335CF6EF.0.1011> with serial 3
    started raft process <82F7529F.0.1011> with serial 1
    started raft process <15170655.0.1011> with serial 2
    raft process <20790EB2.0.1011> has already latest serial. skip it
    get serials (6...8) on <B7995A78.0.1011> to reach the leader's serial:     raft_data_test.go:124: no peers with requested serial

=== FAIL: tests TestRaftLeader (0.21s)

=== Test GenRaft - build quorum, leader election
    cluster with  2 distributed raft processes. no quorum, no leader: OK
    cluster with  3 distributed raft processes. quorum of  3 members with 1 leader: OK
    cluster with  4 distributed raft processes. quorum of  3 members with 1 leader + 1 follower(s):     raft_test.go:246: wrong leader serial

DONE 64 tests, 3 failures in 66.270s
Error: Process completed with exit code 1.
```

**Comment by dulanov** [comment]
It also reproducable locally on dev-machines and also any times with different reasons, like:

```gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -count 1 -short github.com/ergo-services/ergo/tests
✖  tests (53.063s)

=== Failed
=== FAIL: tests TestSagaCancelCases (0.01s)

=== Test GenSagaCancelCases
Starting node: node1GenSagaCancelCases@localhost...OK
Starting node: node2GenSagaCancelCases@localhost...OK
Starting node: node3GenSagaCancelCases@localhost...OK
Starting saga1 on node1GenSagaCancelCases@localhost...OK
Starting saga2 on node2GenSagaCancelCases@localhost...OK
Starting saga3 on node3GenSagaCancelCases@localhost...OK
  Case A (cancel TX on Node1.Saga1): Node1.Saga1 -> cancel -> Node2.Saga2 -> cancel -> Node3.Saga3
    saga_cancel_test.go:343: timed out

=== FAIL: tests TestSagaCommitDistributed (0.01s)

=== Test GenSagaCommitDistributed
Starting node: nodeGenSagaCommitDist01@localhost...OK
Starting node: nodeGenSagaCommitDist02@localhost...OK
... Starting Saga1 processes on node1: OK
... Starting Saga2 processes on node2: OK
... Start new TX on saga1: OK
... Start new worker on saga1: OK
... Start new TX on saga2: OK
... Start new worker on saga2: OK
... Try to send the result on saga1 (must be error ErrSagaTxInProgress):     saga_commit_test.go:234: must be error here

DONE 64 tests, 2 failures in 53.527s```

or (if increase test counts it's absolutely always reproducable)

```
gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -count 1 -short github.com/ergo-services/ergo/tests
✖  tests (1m4.019s)

=== Failed
=== FAIL: tests TestSagaCommitDistributed (0.01s)

=== Test GenSagaCommitDistributed
Starting node: nodeGenSagaCommitDist01@localhost...OK
Starting node: nodeGenSagaCommitDist02@localhost...OK
... Starting Saga1 processes on node1: OK
... Starting Saga2 processes on node2: OK
... Start new TX on saga1: OK
... Start new worker on saga1: OK
... Start new TX on saga2: OK
... Start new worker on saga2: OK
... Try to send the result on saga1 (must be error ErrSagaTxInProgress):     saga_commit_test.go:234: must be error here

DONE 64 tests, 1 failure in 64.492s```
